<?php
	//echo $this->headScript()->appendFile('/js/user/recoverPasswordValidation.js');
	$this->headLink()->appendStylesheet('/css/user/recover-password.css')
?>
	
<div id="wrapRecover">
	<div class="centerRecover">
		<div id="titularWrap">
	    	<div id="titulo">
				<span><?php echo $this->translate("Recordatorio de contraseña"); ?></span>
			</div>
	
	  		<h4><?php echo $this->translate("<strong>¿Olvidaste tu  contraseña</strong> de Portbooker?");?></h4>
	
		</div>
		
		<div id="login"> <?php 
		
			$this->form->prepare();
			echo $this->form()->openTag($this->form);?>
			
			<p class="texto"> <?php 
				echo $this->translate("Si no recuerdas la contraseña de acceso, escribe la dirección email con la que te diste de alta y te facilitaremos el acceso de nuevo:");?>
			</p>
			
			<?php //echo $this->translate("Formulario de recordatorio de Portbooker");?>
			<?php echo $this->formLabel($this->form->get('email')); ?>
			<?php echo $this->formInput($this->form->get('email')); ?>
			<?php echo $this->formElementErrors($this->form->get('email')); ?>
			
			<?php 
			
			if(isset($this->result) and $this->result == 1){
				echo '<p class="error">'.$this->translate("Se ha enviado un email con los datos de acceso a la siguiente dirección").": ".$this ->email.'</p>';
			}
			elseif(isset($this->result) and $this->result == 0){
				if(isset($this-> error) and $this->error){
					echo '<p class="error">'.$this->translate("La dirección de email que nos has facilitado no corresponde a ningun usuario.").'</p>';
				}
				elseif(isset($this->error)) {
					echo '<p class="error">'.$this->translate("Error interno").'</p>';
				}
			}
			?>
			
			<div id="botonLogin"><?php
				echo $this->formRow($this->form->get('botonRecoverPassword'));?>
			</div>
			<?php
				echo $this->form()->closeTag($this->form);
			 ?>
			<br />
			<a href="/<?php echo $this->translate('login_route') ?>" title="<?php echo "Volver" ?>" id="volver"><?php echo $this->translate("Volver a la página inicial");?></a>
			<br />
	
		</div>
	</div>
</div>