<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <?=$this->headMeta()?>
        <?=$this->headTitle()?>
  <!--       <base href="http://<?php //$_SERVER['HTTP_HOST'].$this->baseUrl?>/" />--> 
        <link href="images/layout/favicon.ico" rel="shortcut icon" />
        <?=$this->headStyle()?>
        <?=$this->headLink()?>
  <!--    <link rel="stylesheet" href="css/screen.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="css/print.css" type="text/css" media="print" />   -->  
        <!--[if IE]>
            <link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen, projection" />
        <![endif]-->        
      <!--    <script type="text/javascript">var baseUrl="http://<?php // echo $_SERVER['HTTP_HOST'];?>/";</script>-->
	<!-- 	<script src="js/jquery.js" type="text/javascript"></script>
        <script src="js/jquery.scrollTo.js" type="text/javascript"></script>
        <script src="js/jquery.layout.js" type="text/javascript"></script>  -->
        
    </head>
	
	<body class="<?=$this->lang?>">
        <a id="page-top" name="page-top"></a>
        <div id="layout">
        <div id="header-container">
                <?php //echo $this->render('layout/header')?>
            </div>
			<!-- This is error layout -->
            <div id="wrap" style="padding:2em 0; background-color:#FFF;">
				<?=$this->layout()->content?>
                <div class="clear"></div>
            </div>
            <div id="footer-container">
				<?php //echo $this->render('moorings_footer')?>
            </div> 
    
        </div>
        <?=$this->inlineScript()?>
        
        
       
    </body>
</html>